Controllers/ShoppingController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineShoppingWeb.Models;
using OnlineShoppingWeb.Service;
using OnlineShoppingWeb.ViewModels;
using System.Collections.Generic;
using Microsoft.AspNetCore.Http;
using OnlineShoppingWeb.Helpers;
using System.Linq;
using System.Threading.Tasks;
using System;
using System.Web;


namespace OnlineShoppingWeb.Controllers
{
    [Route("cart")]
    public class ShoppingController : Controller
    //{
    //    private IproductRepository productR;

    //    //private List<ShoppingCartModel> listOfShoppingCartModels;
    //    public ShoppingController(IproductRepository productR)
    //    {
    //        this.productR = productR;
    //    }
    //    public IActionResult Add(int id)
    //    {
    //        var po = productR.GetProduct(id);
    //        if (po == null)
    //        {
    //            List<Product> li = new List<Product>();

    //            ViewBag.carts = li.Count();
    //            HttpContext.Session.SetInt32("id", id);
    //        }
    //        else
    //        {

    //        }
    //        return RedirectToAction("Index", "Home");
    //    }
    //}

    {
        private IproductRepository productR;

        //private List<ShoppingCartModel> listOfShoppingCartModels;
        public ShoppingController(IproductRepository productR)
        {
            this.productR = productR;
        }
        [Route("index")]
        public IActionResult Index()
        {
            var cart = SessionHelpers.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            ViewBag.cart = cart;
            ViewBag.total = cart.Sum(item => item.Product.Price * item.Quantity);
            return View();
        }

        [Route("buy/{id}")]
        public IActionResult Buy(int id)
        {
            //ProductModel productModel = new ProductModel();
            if (SessionHelpers.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart") == null)
            {
                List<Item> cart = new List<Item>();
                cart.Add(new Item { Product = productR.GetProduct(id), Quantity = 1 });
                SessionHelpers.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            else
            {
                List<Item> cart = SessionHelpers.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
                int index = isExist(id);
                if (index != -1)
                {
                    cart[index].Quantity++;
                }
                else
                {
                    cart.Add(new Item { Product = productR.GetProduct(id), Quantity = 1 });
                }
                SessionHelpers.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            return RedirectToAction("Index");
        }

        [Route("remove/{id}")]
        public IActionResult Remove(int id)
        {
            List<Item> cart = SessionHelpers.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            int index = isExist(id);
            cart.RemoveAt(index);
            SessionHelpers.SetObjectAsJson(HttpContext.Session, "cart", cart);
            return RedirectToAction("Index");
        }

        private int isExist(int id)
        {
            List<Item> cart = SessionHelpers.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            for (int i = 0; i < cart.Count; i++)
            {
                if (cart[i].Product.Id.Equals(id))
                {
                    return i;
                }
            }
            return -1;
        }

    } 

}

Views/Shared/_AboutUs.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<p>This is a product showcase</p>
<p>There are over 100 products in this company</p>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlineShoppingWeb</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link rel="stylesheet" href="~/css/Solar.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OnlineShoppingWeb.styles.css" asp-append-version="true" />
    
</head>
<body>
    <header>
       @* <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">OnlineShoppingWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product Update</a>
                        </li>
                        @if(User.Identity.IsAuthenticated)
                        {
                            <li>
                                <a asp-action="LogOut" asp-controller="Account">Log Out</a>
                            </li>
                        }else
                        {
                            <li>
                                <a asp-action="Login" asp-controller="Account">Login</a>
                            </li>
                        }
                    </ul>
                    @Html.Partial("_shoppingCart")
                </div>
            </div>
        </nav>*@
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Navbar</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor03">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product Update</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li>
                                <a asp-action="LogOut" asp-controller="Account">Log Out</a>
                            </li>
                        }
                        else
                        {
                            <li>
                                <a asp-action="Login" asp-controller="Account">Login</a>
                            </li>
                        }
                        
                        <li>
                            @Html.Partial("_shoppingCart")
                        </li>
                    </ul>
                    
                    <br />
                    <form class="d-flex">
                        <input class="form-control me-sm-2" type="text" placeholder="Search">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>
        @if(User.Identity.IsAuthenticated)
        {
            <h4>Welcome @User.Identity.Name</h4>
        }
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - OnlineShoppingWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_shoppingCart.cshtml
<ul class="nav navbar-nav navbar-right">
    <li>
        
    
    @Html.ActionLink("cart", "ShoppingCart", "Shopping", new{id="cartItem"})
    </li>
</ul>